### ISSUE TITLE
Possibility of overriding main classes

### ISSUE THREAD

**Issue by miras4207** [contributte/mailing#6]
The documentation states:

> It has 4 main classes, MailBuilder, MailBuilderFactory, MailSender and MailTemplateFactory. **You can override each of them**.

Could you please provide any working example of this? Is it possible to override `MailBuilder` without overriding the whole `Contributte\Mailing\DI\MailingExtension`?

It seems that `MailingExtension` does not offer any configuration options to actually "override" anything. Perhaps, I am supposed to use some Nette DI features I am not aware of.

Thank your for help.

**Comment by mabar** [comment]
Closed by https://github.com/contributte/mailing/commit/d7a23cef39e1631b964ed551392baa101c1a12c4

It's a nette/di feature. E.g. MailBuilderFactory could be overriden like this:

```yaml
services:
    mailing.builderFactory:
        factory: YourClassImplementingIMailBuilderFactory
```

It's practically same as registering a service in neon, you just reference an existing service by it's name.
